### ISSUE TITLE
node memcached with node-v0.12

### ISSUE THREAD

**Issue by lonso** [3rd-Eden/node-memcached#230]
node memcached can't run on  node v0.12

report this error:
undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE

**Comment by goalsoft** [comment]
In the end there is no maintenance of that mean?

node.js 0.12 Error

Module did not self-register

Why do not fix it?

**Comment by lonso** [comment]
reinstall it's fine.

**Comment by goalsoft** [comment]
reinstall still be wrong

node.js 0.12

Module did not self-register

**Comment by lonso** [comment]
which os?
windows or *inux

**Comment by goalsoft** [comment]
Ubuntu 14.04 64bit

Thanks.

**Comment by 3rd-Eden** [comment]
@lonso ye, it's the downside of a binary modules as they are only build against node version you orginally installed the module with so when you upgrade node versions you usually need to run a new npm install or npm rebuild in order for all dependencies to get rebuild/updated.

**Comment by goalsoft** [comment]
Focus is on

Now node.js 0.12

npm 2.5.0

But there was still Error

If it will not be replaced node.js 0.10.36
