### ISSUE TITLE
memcached.get seems to be non blocking

### ISSUE THREAD

**Issue by wiseflat** [3rd-Eden/node-memcached#241]
Hi,

I am new to memcached. And I realize that node-memcached is working in a non-blocking way.
This is a piece of code, I display on the console test3 before test2...

How can I resolve it ?

```
console.log('test1');
var test = false;
event.forEach(function(item, ind) {        
        self.memcached.get(item.key, function( err, result ){
                if( err ) console.error( err );
                else {
                        switch(item.item){
                                case 'A':
                                        // my code test = true or test = false
                                        console.log('test2');
                                        break;
                                case 'B':
                                        // my code test = true or test = false
                                        console.log('test2');
                                        break;
                        }
                }
        });
});
console.log('test3');
return test;
```

====
BTW, your program is cool dude ;-)

**Comment by ronkorving** [comment]
Every Node.js library on the planet is non-blocking (you may find one or two exceptions to this rule, and you can consider them generally misguided or solving a very unique problem). I suggest you learn about non-blocking Node.js development before targeting your questions at any one library, as your problem would be the same if you were simply trying to read files from a disk using `fs.readFile`.

**Comment by wiseflat** [comment]
Oups, ok ! I am whipping myself with nodejs books right now. It is my punishment for this stupid question.
Thank you for the advice ;-).

**Comment by ronkorving** [comment]
Good luck :)
